#!/bin/bash

echo "Adding '$TOOLBOX' to the PATH"
echo "$PATH" | grep -q "$TOOLBOX" || export PATH="${PATH}:${TOOLBOX}"

function total_usage {
    if test -t -0 ; then
        ls -A
    else
        cat
    fi | \
    tr '\n' '\0' | xargs -0 du -sh 2>/dev/null | sort -hr 
}

function fullest_directories {
    DIR=${1:-.}; shift 2>/dev/null
    # Sorts so that directories that sub-directories appear immediately before their parents
    # awk will only print a line if that line isn't a starting substring of the previous one
    find $DIR -type d 2>/dev/null | sort -r | awk 'a!~"^"$0{a=$0;print}' | total_usage $@
}

alias tu='total_usage'
alias fd='fullest_directories'

# Navigation
alias ll='ls -l'

# Git
alias grc='git clean -fdx'
checkgithome && hash -d git="$GIT_HOME"

# Docker
alias drma='docker rm -f $(docker ps -aq)'

# Builds
alias gw='wrapcall gradle'
alias yw='wrapcall yarn'

# Utils
alias jp='jsonprettyprint'
alias bkp='backup'
  
