#!/bin/bash

echo "Adding '$TOOLBOX' to the PATH"
echo "$PATH" | grep -q "$TOOLBOX" || export PATH="${PATH}:${TOOLBOX}"

function total_usage {
    ls -A | xargs du -s | sort -nrk1,1 | awk '{ N=$1; $1=""; system("echo `numfmt "N"` "$0) }'
}


alias gw='wrapcall gradle'
alias yw='wrapcall yarn'
alias tu='total_usage'
alias jp='jsonprettyprint'

source ${TOOLBOX}/toolbox_aliases
